# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/hopelith"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://instagram.com/username"

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "youtube"
name = "YouTube"
url = "https://youtube.com/@username"

[social.params]
icon = "brand-youtube"